### ISSUE TITLE
check-metadata-urls: Fails to complete

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#929]
The script tools/check-metadata-urls fails to complete. This script is used in cron jobs which checks that the catalog urls actually exist and are sane w r t checksums.

Typical output:

    ........................................................................
    ........................................................................
    ........................................................................
    ........C....C....C.....................................................
    ........................................................................
    Traceback (most recent call last):
      File "/home/runner/work/plugins/plugins/tools/check-metadata-urls", line 200, in <module>
        main()
      File "/home/runner/work/plugins/plugins/tools/check-metadata-urls", line 194, in main
        check_plugin(plugin, path, stats)
      File "/home/runner/work/plugins/plugins/tools/check-metadata-urls", line 168, in check_plugin
        if is_accessible(url, path, "tarball_url", stats):
      File "/home/runner/work/plugins/plugins/tools/check-metadata-urls", line 155, in is_accessible
        status = get_status_code(url.strip())
      File "/home/runner/work/plugins/plugins/tools/check-metadata-urls", line 122, in get_status_code
        conn = httplib.HTTPConnection(url.hostname)
      File "/usr/lib/python3.10/http/client.py", line 851, in __init__
        (self.host, self.port) = self._get_hostport(host, port)
      File "/usr/lib/python3.10/http/client.py", line 885, in _get_hostport
        i = host.rfind(':')
    AttributeError: 'NoneType' object has no attribute 'rfind'
    ................

**Comment by leamas** [comment]
BTW: Current, relevant output: 

    Checksum errors:

    metadata/ais-vd-1.8.2-android-arm64-A64-16.xml: ais-vd-1.8.2_android-arm64-16-arm64.tar.gz
            metadata checksum: '40a2fdb9677eb26d5e19fd57c29c94f4750be3ac8f030e5c7f3ae0fbf35be8d6'
            computed checksum: '6586884bfa1df070f572593670cbddecf5ecbcb2df49bb2ff3ee206901dca42f'
    metadata/ais-vd-1.8.2-darwin-wx32-10.xml: ais-vd-1.8.2_darwin-wx32-10-x86_64.tar.gz
            metadata checksum: '1faea89195b87c21829d824ad3639840f190a864d6e5db7984a02da7dbcf918b'
            computed checksum: 'bac0635d208d98d1bf3eb5b935a1253702f01fe66c3eecf6951c43d53e448ba0'
    metadata/ais-vd-1.8.2-debian-A32-11.xml: ais-vd-1.8.2_debian-11-armhf.tar.gz
            metadata checksum: '9bbd8196daa73951f8e56746c5deb11b038eb18abdde5913000259939b26b4db'
            computed checksum: '642a732a071388b4befb59fd9e9aa02d182562172ba3d65bc458fffde7def06a'
    metadata/CanadianTides-v0.6.0-debian-10.xml: CanadianTides-v0.6.0_debian-10-x86_64.tar.gz
            metadata checksum: '8e2247049c17505e976d17b8deafb667d3271d170ccd19ebeee6f43033ebe5fa'
            computed checksum: '8b107ab5b6e73ad7524164c9cb041d93ad5b52f6121d056eb0e8c13338978a01'
    metadata/CanadianTides-v0.6.0-debian-11.xml: CanadianTides-v0.6.0_debian-11-x86_64.tar.gz
            metadata checksum: '4e800568e616b88c997e53a0051927ec9a667a3366c44f75c61c52ec06ddd57a'
            computed checksum: '82c798cb76a458944b9082cd965794e7a9b40f9873706f0dd949f8fb478cdc7f'
    metadata/CanadianTides-v0.6.0-msvc-10.0.14393.xml: CanadianTides-v0.6.0_msvc-10.0.14393-win32.tar.gz
            metadata checksum: '4263f754fe1a8ed92a6c6b5497dbf3511da88a67a45f65c744999a208886c634'
            computed checksum: '0278b104ad036f3882d796ff4a2c36b55332dcf9c44c2c0f3a24968770e0f951'
    metadata/CanadianTides-v0.6.0-ubuntu-18.04.xml: CanadianTides-v0.6.0_ubuntu-18.04-x86_64.tar.gz
            metadata checksum: 'add40b0a0b92d55271c03216102d8cf46afb7664931ae41006581fa771dacb93'
            computed checksum: '4d834bd0573261ad0b08a6a46a2c4ba1a380e73efa8e287027968acd37e8b2e9'
    metadata/CanadianTides-v0.6.0-ubuntu-gtk3-18.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-18.04-x86_64.tar.gz
            metadata checksum: 'c20a5d876cd5f3502ca6f0825ead54b5dd661b2f3be78c9304e53eb321e32e77'
            computed checksum: 'e83c21b886c085f7d7b2712c6715ee02c9b44a71ee2b119f27e3f265e253d4a8'
    metadata/CanadianTides-v0.6.0-ubuntu-gtk3-20.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-20.04-x86_64.tar.gz
            metadata checksum: '49acb0c700dff37761f76cba5a3ddc01c434f9f566299ab597c22c522fd90782'
            computed checksum: '0ccbf8c41661a5acfee85f487ab01fba181def43a6eac7106891b12b623c7b99'
    metadata/CanadianTides-v0.6.0-ubuntu-gtk3-A32-20.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-20.04-armhf.tar.gz
            metadata checksum: 'a74370d04203729db9899fb5b340c459ae953ad672aba639489ad4fcbfe5c67d'
            computed checksum: '29c2cc6fea9bff7ccafc13abee90152374552f68a102b5e623d37cc745bb5500'

**Comment by leamas** [comment]
Filed https://github.com/Hakansv/ais-vd_pi/issues/9 and https://github.com/Rasbats/CanadianTides_pi/issues/2
